services:
  routinator:
    image: "nlnetlabs/routinator"
    volumes:
      - json-cache:/json/cache
    ports:
      - 8323:8323
    logging:
      driver: "none"
  rtrtr:
    image: "nlnetlabs/rtrtr"
    command: ["--config", "/cache/rtrtr.conf"]
    volumes:
      - ./config/rtrtr.conf:/cache/rtrtr.conf
  # Add once blockchain works
  bird2:
    image: my-bird:latest
    container_name: bird2-router
    network_mode: "bridge"
    volumes:
      - ./config/bird.conf:/etc/bird/bird.conf
    restart: unless-stopped
  blockchain:
    build: "./"
    volumes:
      - json-cache:/json/cache
    # Allows output on terminal
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  json-cache: